# Generated by Django 4.1.5 on 2023-01-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='grayscale',
            field=models.ImageField(blank=True, upload_to='images/grayscale/'),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.FileField(default='1', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='large',
            field=models.ImageField(blank=True, upload_to='images/large/'),
        ),
        migrations.AddField(
            model_name='image',
            name='medium',
            field=models.ImageField(blank=True, upload_to='images/medium/'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/thumbnail/'),
        ),
    ]
