# Generated by Django 4.1.5 on 2023-01-25 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageUploader', '0002_image_grayscale_image_image_image_large_image_medium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
    ]
