# Generated by Django 4.1.5 on 2023-01-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageUploader', '0003_remove_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='grayscale',
        ),
        migrations.RemoveField(
            model_name='image',
            name='large',
        ),
        migrations.RemoveField(
            model_name='image',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail',
        ),
    ]
