# Generated by Django 4.1.5 on 2023-01-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUploader', '0004_remove_image_grayscale_remove_image_large_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='grayscale',
            field=models.ImageField(blank=True, upload_to='images/grayscale/'),
        ),
        migrations.AddField(
            model_name='image',
            name='large',
            field=models.ImageField(blank=True, upload_to='images/large/'),
        ),
        migrations.AddField(
            model_name='image',
            name='medium',
            field=models.ImageField(blank=True, upload_to='images/medium/'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/thumbnail/'),
        ),
    ]
