# Generated by Django 4.1.5 on 2023-01-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageUploader', '0005_image_grayscale_image_large_image_medium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='grayscale',
        ),
        migrations.RemoveField(
            model_name='image',
            name='large',
        ),
        migrations.RemoveField(
            model_name='image',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail',
        ),
    ]
